### ISSUE TITLE
v0.2.0 Todo List

### ISSUE THREAD

**Issue by tneotia** [BlueBubblesApp/bluebubbles-server#224]
- [x] Add CORS so we can use API stuff on Web (then make a build for Tanay :P)
- [x] https://github.com/BlueBubblesApp/bluebubbles-server/issues/193
- [x] Settings & Theming import / export endpoint
- [x] Settings limit and offset on `get-chats` doesn't return particpants
- [x] Sort `get-chats` by lastMessageDate
- [x] Send server stats (messages, top group, etc) in `server-metadata` request
- [x] Fix localtunnel doesn't work with API
- [x] Change `get-contacts-from-db` socket to just take a list of strings rather than the `Handle` object itself, and find a good way to return the first and last names so it can be easily parsed client side

**Comment by zlshames** [comment]
- [ ] update themes repo with folders for screenshots

**Comment by zlshames** [comment]
Finished endpoint to check for a server update

**Comment by zlshames** [comment]
*[] fix private API status in server metadata

**Comment by zlshames** [comment]
I added 3 endpoints to fetch server statistics from

**Comment by zlshames** [comment]
Added a "sort" parameter to the post to `/chat/query` which you can pass it "lastMessage" to sort by that created field

**Comment by zlshames** [comment]
`get-contacts-from-db` should take both a list of dicts or strings
