### ISSUE TITLE
Next Update(s) Checklist

### ISSUE THREAD

**Issue by tneotia** [BlueBubblesApp/bluebubbles-server#467]
- [x] A failed recurring scheduled message appears to send infinitely. Reproduced by creating recurring via API and accidentally setting method as "applescript", not "apple-script".
- [x] Add a way to edit an existing scheduled message by ID?
- [x] Sent attachments on Monterey and Ventura aren't copied by iMessage into their correct directory
- [x] FaceTime notification support
- [x] One-time messages completely hang the server when sending
- [x] Scheduling recurring messages via the server UI is broken in a few ways

**Comment by zlshames** [comment]
Can't reproduce the infinite resending on error. Waiting for feedback on new build
